export { EmailForm } from "./components/EmailForm"
export { Footer } from "./components/Footer"
export { Gaufre } from "./components/Gaufre"
export { Header } from "./components/Header"
export { Homepage } from "./components/Homepage"
export { HomepageContent } from "./components/HomepageContent"
export { ProconnectButton } from "./components/ProconnectButton"
export { Email as HomepageEmail } from "./components/Homepage/Email"
export { EmailOrProconnect as HomepageEmailOrProconnect } from "./components/Homepage/EmailOrProconnect"
export { Proconnect as HomepageProconnect } from "./components/Homepage/Proconnect"
export { LaSuiteTranslationsProvider, useTranslate } from "./i18n/useTranslate"
export { default as frTranslations } from "./i18n/fr.json"
